package kafku

// DefaultConfigVars are the custom config vars to be read into Viper
var DefaultConfigVars = Vars{
	Port:                        "8000",
	DocsFile:                    "index.html",
	KafkaTopics:                 "",
	KafkaBrokers:                "",
	KafkaClientID:               "",
	KafkaGroupID:                "",
	RevealVars:                  "KAFKA_BROKERS,KAFKA_TOPICS,KAFKA_CLIENT_ID,KAFKA_GROUP_ID",
	GMDataAddr:                  "",
	GmDataDerivativeAddr:        "",
	MimeTopics:                  "",
	FallbackTopic:               "",
	SpacyURL:                    "",
	SpacyBodySize:               "40000",
	CogitoURL:                   "",
	CogitoBodySize:              "40000",
	InternalServerName:          "",
	InternalServerCrtPath:       "",
	InternalServerKeyPath:       "",
	InternalCaCrtPath:           "",
	InternalTLSOn:               "false",
	ExternalSourceServerName:    "",
	ExternalSourceServerCrtPath: "",
	ExternalSourceServerKeyPath: "",
	ExternalSourceCaCrtPath:     "",
	ChangelogPath:               "Changelog.md",
	IndexName:                   "",
	DocType:                     "",
	Derivtype:                   "",
	DType:                       "",
	SpacyEndpoint:               "",
	RowDtype:                    "",
}
