apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goku-chart.fullname" . }}
  labels:
    {{- include "goku-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "goku-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "goku-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "goku-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.goku.image }}:{{ .Values.goku.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.goku.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.goku.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /goku
              port: http
          readinessProbe:
            httpGet:
              path: /goku
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
