apiVersion: v1
kind: Service
metadata:
  name: {{ include "goku-chart.fullname" . }}
  labels:
    {{- include "goku-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.goku.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "goku-chart.selectorLabels" . | nindent 4 }}